bbl_web_homepage:
    pattern:  /
    defaults: { _controller: BBLWebBundle:Main:index }
    
profil:
    pattern:  /profil/{name}
    defaults: { _controller: BBLWebBundle:Main:profil }
    
registry:
    pattern: /signup
    defaults: { _controller: BBLWebBundle:Main:signup }
    
regart:
    pattern: /artist
    defaults: { _controller: BBLWebBundle:Main:regArt }
    
regsou:
    pattern: /source
    defaults: { _controller: BBLWebBundle:Main:regSou }
    
ajax_load:
  pattern: /load
  defaults: { _controller: BBLWebBundle:Load:load }
  requirements:
    _method: POST
  
login:
  pattern: /login
  defaults: { _controller: BBLWebBundle:Ajax:login}
  requirements:
    _method: POST
 
logout:
  pattern: /logout
  defaults: { _controller: BBLWebBundle:Main:logout}
  
signUp:
   pattern: /reg
   defaults: { _controller: BBLWebBundle:Main:reg}
   requirements:
    _method: POST
   
