bbl_web_homepage:
    pattern:  /
    defaults: { _controller: BBLWebBundle:Main:index }
    
    
profil:
    pattern:  /profil/{name}
    defaults: { _controller: BBLWebBundle:Main:profil }
    
registry:
    pattern: /signup
    defaults: { _controller: BBLWebBundle:Main:signup }
    
regart:
    pattern: /artist
    defaults: { _controller: BBLWebBundle:Main:regArt }
    
regsou:
    pattern: /source
    defaults: { _controller: BBLWebBundle:Main:regSou }
    
ajax_load:
  pattern: /load
  defaults: { _controller: BBLWebBundle:Load:load }
  requirements:
    _method: POST
  
login:
  pattern: /login
  defaults: { _controller: BBLWebBundle:Ajax:login}
  requirements:
    _method: POST
 
logout:
  pattern: /logout
  defaults: { _controller: BBLWebBundle:Main:logout}
  
signUp:
   pattern: /reg
   defaults: { _controller: BBLWebBundle:Main:reg}
   requirements:
    _method: POST
    
picupload:
   pattern: /picup
   defaults: { _controller: BBLWebBundle:File:picUp}
   requirements:
    _method: POST
   
musicupload:
   pattern: /musicup
   defaults: { _controller: BBLWebBundle:File:musicUp}
   requirements:
    _method: POST
    
test:
   pattern: /test
   defaults: { _controller: BBLWebBundle:File:test}
   
testm:
   pattern: /testm
   defaults: { _controller: BBLWebBundle:File:musicTest}
   
fillSource:
   pattern: /fillsource
   defaults: { _controller: BBLWebBundle:Load:fillSource}
   requirements:
    _method: POST
   
fillArtist:
   pattern: /fillartist
   defaults: { _controller: BBLWebBundle:Load:fillArtist}
   requirements:
    _method: POST
   
   
