bbl_web_homepage:
    pattern:  /
    defaults: { _controller: BBLWebBundle:Main:index }
    
registry:
    pattern: /reg
    defaults: { _controller: BBLWebBundle:Main:reg }
    
ajax_load:
  pattern: /load
  defaults: { _controller: BBLWebBundle:Ajax:load }