bbl_web_homepage:
    pattern:  /
    defaults: { _controller: BBLWebBundle:Main:index }
    
registry:
    pattern: /signup
    defaults: { _controller: BBLWebBundle:Main:reg }
    
ajax_load:
  pattern: /load
  defaults: { _controller: BBLWebBundle:Ajax:load }
  
login:
  pattern: /login
  defaults: { _controller: BBLWebBundle:Ajax:login}
  
signUp:
   pattern: /signUp
   defaults: { _controller: BBLWebBundle:Main:signUp}
  